/**
 * Shop Networks Configuration
 *
 * Derived from Qual Planner Master CSV columns AN-DH (data tape shop columns)
 * This defines the hierarchical organization: Network → Child Location
 *
 * AITX-owned shops are internal, all others are 3rd party
 */

export interface ShopLocation {
  name: string;
  code: string;
  city: string;
  state: string;
  region: string;
  servingRailroad?: string;
  tankQualified: boolean;
  monthlyCapacity: number;
  costIndex: number;
}

export interface ShopNetwork {
  id: string;
  name: string;
  code: string;
  isAitxInternal: boolean;
  annualTargetVolume: number;
  costIndex: number;
  notes: string;
  locations: ShopLocation[];
}

// AITX Internal Network (owned shops)
export const AITX_NETWORK: ShopNetwork = {
  id: 'aitx',
  name: 'AITX',
  code: 'AITX',
  isAitxInternal: true,
  annualTargetVolume: 2400,
  costIndex: 1.379,
  notes: 'AITX owned and operated facilities',
  locations: [
    {
      name: 'AITX Fleet Services of Canada Inc.',
      code: 'AITX-SARNIA',
      city: 'Sarnia',
      state: 'ON',
      region: 'Canada',
      servingRailroad: 'CN',
      tankQualified: true,
      monthlyCapacity: 25,
      costIndex: 1.379,
    },
    {
      name: 'AITX Railcar Services LLC',
      code: 'AITX-NKC',
      city: 'N Kansas City',
      state: 'MO',
      region: 'Midwest',
      servingRailroad: 'BNSF',
      tankQualified: true,
      monthlyCapacity: 30,
      costIndex: 1.379,
    },
    {
      name: 'AITX Mini/Mobile Unit 93',
      code: 'AITX-MOUNDS',
      city: 'Mounds',
      state: 'OK',
      region: 'Southwest',
      servingRailroad: 'BNSF',
      tankQualified: true,
      monthlyCapacity: 10,
      costIndex: 1.379,
    },
    {
      name: 'AITX Mobile Headquarters',
      code: 'AITX-LAPORTE',
      city: 'LaPorte',
      state: 'TX',
      region: 'Southwest',
      servingRailroad: 'UP',
      tankQualified: true,
      monthlyCapacity: 15,
      costIndex: 1.379,
    },
    {
      name: 'AITX Mobile Operations',
      code: 'AITX-HOUSTON',
      city: 'Houston',
      state: 'TX',
      region: 'Southwest',
      servingRailroad: 'UP',
      tankQualified: true,
      monthlyCapacity: 15,
      costIndex: 1.379,
    },
    {
      name: 'AITX Railcar Services LLC',
      code: 'AITX-BROOKHAVEN',
      city: 'Brookhaven',
      state: 'MS',
      region: 'Southeast',
      servingRailroad: 'CN',
      tankQualified: true,
      monthlyCapacity: 35,
      costIndex: 1.379,
    },
    {
      name: 'AITX Railcar Services LLC',
      code: 'AITX-BUDE',
      city: 'Bude',
      state: 'MS',
      region: 'Southeast',
      servingRailroad: 'CN',
      tankQualified: true,
      monthlyCapacity: 35,
      costIndex: 1.379,
    },
    {
      name: 'AITX Railcar Services LLC',
      code: 'AITX-LONGVIEW',
      city: 'Longview',
      state: 'TX',
      region: 'Southwest',
      servingRailroad: 'UP',
      tankQualified: true,
      monthlyCapacity: 30,
      costIndex: 1.379,
    },
    {
      name: 'AITX Railcar Services LLC',
      code: 'AITX-TENNILLE',
      city: 'Tennille',
      state: 'GA',
      region: 'Southeast',
      servingRailroad: 'NS',
      tankQualified: true,
      monthlyCapacity: 25,
      costIndex: 1.379,
    },
    {
      name: 'AITX Repair-KCK MRU',
      code: 'AITX-KCK',
      city: 'Kansas City',
      state: 'KS',
      region: 'Midwest',
      servingRailroad: 'BNSF',
      tankQualified: true,
      monthlyCapacity: 10,
      costIndex: 1.379,
    },
    {
      name: 'AITX Repair-Milton, PA MRU',
      code: 'AITX-MILTON',
      city: 'Milton',
      state: 'PA',
      region: 'Northeast',
      servingRailroad: 'NS',
      tankQualified: true,
      monthlyCapacity: 10,
      costIndex: 1.379,
    },
    {
      name: 'AITX Repair-Sweetwater, TX MRU',
      code: 'AITX-SWEETWATER',
      city: 'Sweetwater',
      state: 'TX',
      region: 'Southwest',
      servingRailroad: 'UP',
      tankQualified: true,
      monthlyCapacity: 10,
      costIndex: 1.379,
    },
  ],
};

// Third Party Networks
export const THIRD_PARTY_NETWORKS: ShopNetwork[] = [
  {
    id: 'trinity',
    name: 'Trinity',
    code: 'TRINITY',
    isAitxInternal: false,
    annualTargetVolume: 1800,
    costIndex: 1.05,
    notes: 'Major 3P partner with multiple locations',
    locations: [
      {
        name: 'Trinity Industries, Inc.',
        code: 'TRI-FTWORTH',
        city: 'Ft. Worth',
        state: 'TX',
        region: 'Southwest',
        servingRailroad: 'UP',
        tankQualified: true,
        monthlyCapacity: 40,
        costIndex: 1.05,
      },
      {
        name: 'Trinity Industries, Inc.',
        code: 'TRI-SAGINAW',
        city: 'Saginaw',
        state: 'MI',
        region: 'Midwest',
        servingRailroad: 'NS',
        tankQualified: true,
        monthlyCapacity: 35,
        costIndex: 1.05,
      },
      {
        name: 'Trinity Rail Services',
        code: 'TRI-SHELLROCK',
        city: 'Shell Rock',
        state: 'IA',
        region: 'Midwest',
        servingRailroad: 'UP',
        tankQualified: true,
        monthlyCapacity: 30,
        costIndex: 1.05,
      },
      {
        name: 'Trinity Rail - Sunray',
        code: 'TRI-SUNRAY',
        city: 'Sunray',
        state: 'TX',
        region: 'Southwest',
        servingRailroad: 'BNSF',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.05,
      },
    ],
  },
  {
    id: 'greenbrier',
    name: 'Greenbrier',
    code: 'GREENBRIER',
    isAitxInternal: false,
    annualTargetVolume: 1200,
    costIndex: 1.08,
    notes: 'Rail services and manufacturing',
    locations: [
      {
        name: 'Greenbrier Repair & Services',
        code: 'GBR-CLEBURNE',
        city: 'Cleburne',
        state: 'TX',
        region: 'Southwest',
        servingRailroad: 'BNSF',
        tankQualified: true,
        monthlyCapacity: 30,
        costIndex: 1.08,
      },
      {
        name: 'Greenbrier Repair & Services',
        code: 'GBR-FINLEY',
        city: 'Finley',
        state: 'ND',
        region: 'Midwest',
        servingRailroad: 'BNSF',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.08,
      },
      {
        name: 'Greenbrier Repair-Central',
        code: 'GBR-MARMADUKE',
        city: 'Marmaduke',
        state: 'AR',
        region: 'Southeast',
        servingRailroad: 'BNSF',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.08,
      },
      {
        name: 'Greenbrier Rail Services',
        code: 'GBR-OMAHA',
        city: 'Omaha',
        state: 'NE',
        region: 'Midwest',
        servingRailroad: 'UP',
        tankQualified: true,
        monthlyCapacity: 30,
        costIndex: 1.08,
      },
    ],
  },
  {
    id: 'eagle',
    name: 'Eagle Railcar',
    code: 'EAGLE',
    isAitxInternal: false,
    annualTargetVolume: 2400,
    costIndex: 1.00,
    notes: 'Largest 3P network by location count',
    locations: [
      {
        name: 'Eagle Railcar',
        code: 'EGL-CAIRO',
        city: 'Cairo',
        state: 'GA',
        region: 'Southeast',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar (Channelview)',
        code: 'EGL-CHANNELVIEW',
        city: 'Eastland',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar',
        code: 'EGL-DUBOIS',
        city: 'DuBois',
        state: 'PA',
        region: 'Northeast',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar',
        code: 'EGL-ELKHART',
        city: 'Elkhart',
        state: 'IN',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar',
        code: 'EGL-FITZGERALD',
        city: 'Fitzgerald',
        state: 'GA',
        region: 'Southeast',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar',
        code: 'EGL-GORDON',
        city: 'Gordon',
        state: 'GA',
        region: 'Southeast',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar',
        code: 'EGL-JUNCTIONCITY',
        city: 'Junction City',
        state: 'KS',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar',
        code: 'EGL-LONGVIEW',
        city: 'Longview',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar-Georgetown/Orange',
        code: 'EGL-GEORGETOWN',
        city: 'Georgetown',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar Services',
        code: 'EGL-ORANGE',
        city: 'Orange',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar Services',
        code: 'EGL-ROSCOE',
        city: 'Roscoe',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar',
        code: 'EGL-WASHINGTON',
        city: 'Washington',
        state: 'IN',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
      {
        name: 'Eagle Railcar',
        code: 'EGL-WICHITAFALLS',
        city: 'Wichita Falls',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.00,
      },
    ],
  },
  {
    id: 'cathcart',
    name: 'Cathcart',
    code: 'CATHCART',
    isAitxInternal: false,
    annualTargetVolume: 1500,
    costIndex: 1.03,
    notes: 'Multi-region coverage',
    locations: [
      {
        name: 'Cathcart (Amarillo)',
        code: 'CTH-AMARILLO',
        city: 'Amarillo',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.03,
      },
      {
        name: 'Cathcart (Elk Mills)',
        code: 'CTH-ELKMILLS',
        city: 'Elk Mills',
        state: 'MD',
        region: 'Northeast',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.03,
      },
      {
        name: 'Cathcart - Hinton',
        code: 'CTH-HINTON',
        city: 'Hinton',
        state: 'AB',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.03,
      },
      {
        name: 'Cathcart (Lynchburg)',
        code: 'CTH-LYNCHBURG',
        city: 'Lynchburg',
        state: 'VA',
        region: 'Southeast',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.03,
      },
      {
        name: 'Cathcart - Kansas City',
        code: 'CTH-KC',
        city: 'Kansas City',
        state: 'MO',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.03,
      },
      {
        name: 'Cathcart - Maumee',
        code: 'CTH-MAUMEE',
        city: 'Maumee',
        state: 'OH',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.03,
      },
      {
        name: 'Cathcart Rail - Hastings',
        code: 'CTH-HASTINGS',
        city: 'Hastings',
        state: 'NE',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.03,
      },
    ],
  },
  {
    id: 'curry',
    name: 'Curry Rail Services',
    code: 'CURRY',
    isAitxInternal: false,
    annualTargetVolume: 900,
    costIndex: 1.02,
    notes: 'Regional specialist',
    locations: [
      {
        name: 'Curry Rail Services - Hollidaysburg PA',
        code: 'CRY-HOLLIDAYSBURG',
        city: 'Hollidaysburg',
        state: 'PA',
        region: 'Northeast',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.02,
      },
      {
        name: 'Curry Rail Services Hockley',
        code: 'CRY-HOCKLEY',
        city: 'Hockley',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 30,
        costIndex: 1.02,
      },
      {
        name: 'Curry Rail Services Shoshoni',
        code: 'CRY-SHOSHONI',
        city: 'Shoshoni',
        state: 'WY',
        region: 'West',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.02,
      },
    ],
  },
  {
    id: 'procor',
    name: 'Procor',
    code: 'PROCOR',
    isAitxInternal: false,
    annualTargetVolume: 1200,
    costIndex: 1.10,
    notes: 'Canadian and Western US coverage',
    locations: [
      {
        name: 'Procor Limited',
        code: 'PRO-NVAN',
        city: 'N. Van',
        state: 'BC',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.10,
      },
      {
        name: 'Procor Limited',
        code: 'PRO-JOFFRE',
        city: 'Joffre',
        state: 'AB',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 30,
        costIndex: 1.10,
      },
      {
        name: 'Procor Limited',
        code: 'PRO-SARNIA',
        city: 'Sarnia',
        state: 'ON',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 30,
        costIndex: 1.10,
      },
      {
        name: 'Procor - Transmark',
        code: 'PRO-LETHBRIDGE',
        city: 'Lethbridge',
        state: 'AB',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.10,
      },
    ],
  },
  {
    id: 'transco',
    name: 'Transco',
    code: 'TRANSCO',
    isAitxInternal: false,
    annualTargetVolume: 1500,
    costIndex: 0.98,
    notes: 'Cost-effective regional coverage',
    locations: [
      {
        name: 'Transco',
        code: 'TRC-TEXARKANA',
        city: 'Texarkana',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 30,
        costIndex: 0.98,
      },
      {
        name: 'Transco Rail',
        code: 'TRC-SAYRE',
        city: 'Sayre',
        state: 'OK',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 0.98,
      },
      {
        name: 'Transco Railway',
        code: 'TRC-OELWEIN',
        city: 'Oelwein',
        state: 'IA',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 0.98,
      },
      {
        name: 'Transco Railway Products, Inc.',
        code: 'TRC-MILESCITY',
        city: 'Miles City',
        state: 'MT',
        region: 'West',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 0.98,
      },
      {
        name: 'Transco-Sheldon, TX',
        code: 'TRC-SHELDON',
        city: 'Houston',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 0.98,
      },
    ],
  },
  {
    id: 'other-3p',
    name: 'Other 3rd Party',
    code: 'OTHER',
    isAitxInternal: false,
    annualTargetVolume: 2000,
    costIndex: 1.05,
    notes: 'Individual 3P shops',
    locations: [
      {
        name: 'Apache Railway - Snowflake AZ',
        code: 'APACHE-SNOWFLAKE',
        city: 'Snowflake',
        state: 'AZ',
        region: 'West',
        tankQualified: true,
        monthlyCapacity: 15,
        costIndex: 1.00,
      },
      {
        name: 'Blastech Corp',
        code: 'BLAST-BRANTFORD',
        city: 'Brantford',
        state: 'ON',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.05,
      },
      {
        name: 'CAD Railway Services',
        code: 'CAD-LACHINE',
        city: 'Lachine',
        state: 'QC',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.08,
      },
      {
        name: 'CALTRAX, Inc.',
        code: 'CALTRAX-CALGARY',
        city: 'Calgary',
        state: 'AB',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.05,
      },
      {
        name: 'CANDO Rail Services',
        code: 'CANDO-OAKBANK',
        city: 'Oakbank',
        state: 'MB',
        region: 'Canada',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.08,
      },
      {
        name: 'Frit Car and Equipment, Inc.',
        code: 'FRIT-BREWTON',
        city: 'Brewton',
        state: 'AL',
        region: 'Southeast',
        tankQualified: true,
        monthlyCapacity: 15,
        costIndex: 0.95,
      },
      {
        name: 'Frit Car and Equipment, Inc.',
        code: 'FRIT-BRIDGETON',
        city: 'Bridgeton',
        state: 'NJ',
        region: 'Northeast',
        tankQualified: true,
        monthlyCapacity: 15,
        costIndex: 0.95,
      },
      {
        name: 'H.C. Chandler and Son, Inc.',
        code: 'HCC-PLANTERSVILLE',
        city: 'Plantersville',
        state: 'AL',
        region: 'Southeast',
        tankQualified: true,
        monthlyCapacity: 15,
        costIndex: 0.92,
      },
      {
        name: 'Iron Horse Rail Services',
        code: 'IRONHORSE-BEAUMONT',
        city: 'Beaumont',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.00,
      },
      {
        name: 'KRS Katahdin Railcar Services',
        code: 'KRS-BANGOR',
        city: 'Bangor',
        state: 'ME',
        region: 'Northeast',
        tankQualified: true,
        monthlyCapacity: 15,
        costIndex: 1.05,
      },
      {
        name: 'Midwest Railcar Repair, Inc.',
        code: 'MWR-BRANDON',
        city: 'Brandon (Corson)',
        state: 'SD',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 0.98,
      },
      {
        name: 'PSC Repair',
        code: 'PSC-BEAUMONT',
        city: 'Beaumont',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.00,
      },
      {
        name: 'Rescar',
        code: 'RESCAR-SAVANNA',
        city: 'Savanna',
        state: 'IL',
        region: 'Midwest',
        tankQualified: true,
        monthlyCapacity: 25,
        costIndex: 1.02,
      },
      {
        name: 'TLC Rail Services/Inserv-Wright City',
        code: 'TLC-WRIGHTCITY',
        city: 'Wright City',
        state: 'OK',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 0.95,
      },
      {
        name: 'TMC Engineering Services',
        code: 'TMC-HOUSTON',
        city: 'Houston',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.05,
      },
      {
        name: 'TNT Repair Services',
        code: 'TNT-LONGVIEW',
        city: 'Longview',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 0.98,
      },
      {
        name: 'Transitech, Inc.',
        code: 'TRANSITECH-FORDYCE',
        city: 'Fordyce',
        state: 'AR',
        region: 'Southeast',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 0.95,
      },
      {
        name: 'Red River Coatings',
        code: 'RRC-NASH',
        city: 'Nash',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 15,
        costIndex: 1.00,
      },
      {
        name: 'Rescar #380',
        code: 'RESCAR-DEERPARK',
        city: 'Deer Park',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 20,
        costIndex: 1.02,
      },
      {
        name: 'Texana Midway Tank Cleaning',
        code: 'TEXANA-TEXARKANA',
        city: 'Texarkana',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 15,
        costIndex: 0.90,
      },
      {
        name: 'VLS RECOVERY SERVICES - Hockley',
        code: 'VLS-HOCKLEY',
        city: 'Hockley',
        state: 'TX',
        region: 'Southwest',
        tankQualified: true,
        monthlyCapacity: 15,
        costIndex: 0.95,
      },
    ],
  },
];

// All networks combined
export const ALL_NETWORKS: ShopNetwork[] = [AITX_NETWORK, ...THIRD_PARTY_NETWORKS];

// CSV column name to shop code mapping (from Qual Planner Master columns AN-DH)
export const CSV_SHOP_COLUMN_MAPPING: Record<string, string> = {
  'AITX Fleet Services of Canada Inc. (Sarnia)': 'AITX-SARNIA',
  'AITX Railcar Services LLC (N Kansas City)': 'AITX-NKC',
  'AITX Mini/Mobile Unit 93 (Mounds)': 'AITX-MOUNDS',
  'AITX Mobile Headquarters (LaPorte)': 'AITX-LAPORTE',
  'AITX Mobile Operations (Houston)': 'AITX-HOUSTON',
  'AITX Railcar Services LLC (Brookhaven)': 'AITX-BROOKHAVEN',
  'AITX Railcar Services LLC (Bude)': 'AITX-BUDE',
  'AITX Railcar Services LLC (Longview)': 'AITX-LONGVIEW',
  'AITX Railcar Services LLC (Tennille)': 'AITX-TENNILLE',
  'AITX Repair-KCK MRU (Kansas City)': 'AITX-KCK',
  'AITX Repair-Milton, PA MRU': 'AITX-MILTON',
  'AITX Repair-Sweetwater, TX MRU ': 'AITX-SWEETWATER',
  'Apache Railway - Snowflake AZ (Snowflake)': 'APACHE-SNOWFLAKE',
  'Blastech Corp (BRANTFORD)': 'BLAST-BRANTFORD',
  'CAD Railway Services (Lachine, Montreal)': 'CAD-LACHINE',
  'CALTRAX, Inc. (Calgary)': 'CALTRAX-CALGARY',
  'CANDO Rail Services (Oakbank)': 'CANDO-OAKBANK',
  'Cathcart (Amarillo) (Amarillo)': 'CTH-AMARILLO',
  'Cathcart (Elk Mills) (Elk Mills)': 'CTH-ELKMILLS',
  'Cathcart - Hinton (Hinton)': 'CTH-HINTON',
  'Cathcart (Lynchburg) (Lynchburg)': 'CTH-LYNCHBURG',
  'Cathcart - Kansas City (Kansas City)': 'CTH-KC',
  'Cathcart - Maumee (Maumee)': 'CTH-MAUMEE',
  'Cathcart Rail - Hastings (Hastings)': 'CTH-HASTINGS',
  'Curry Rail Services - Hollidaysburg PA (Hollidaysburg)': 'CRY-HOLLIDAYSBURG',
  'Curry Rail Services Hockley (Hockley)': 'CRY-HOCKLEY',
  'Curry Rail Services Shoshoni (Shoshoni)': 'CRY-SHOSHONI',
  'Eagle Railcar (Cairo)': 'EGL-CAIRO',
  'Eagle Railcar (Channelview) (Eastland)': 'EGL-CHANNELVIEW',
  'Eagle Railcar (DuBois)': 'EGL-DUBOIS',
  'Eagle Railcar (Elkhart)': 'EGL-ELKHART',
  'Eagle Railcar (Fitzgerald)': 'EGL-FITZGERALD',
  'Eagle Railcar (Gordon)': 'EGL-GORDON',
  'Eagle Railcar (Junction City)': 'EGL-JUNCTIONCITY',
  'Eagle Railcar (Longview)': 'EGL-LONGVIEW',
  'Eagle Railcar-Georgetown/Orange (Georgetown)': 'EGL-GEORGETOWN',
  'Eagle Railcar Services (Orange)': 'EGL-ORANGE',
  'Eagle Railcar Services (Roscoe)': 'EGL-ROSCOE',
  'Eagle Railcar (Washington)': 'EGL-WASHINGTON',
  'Eagle Railcar (Wichita Falls)': 'EGL-WICHITAFALLS',
  'Frit Car and Equipment, Inc. (Brewton)': 'FRIT-BREWTON',
  'Frit Car and Equipment, Inc. (Bridgeton)': 'FRIT-BRIDGETON',
  'Greenbrier Repair & Services (Cleburne)': 'GBR-CLEBURNE',
  'Greenbrier Repair & Services (Finley)': 'GBR-FINLEY',
  'Greenbrier Repair-Central (Marmaduke)': 'GBR-MARMADUKE',
  'Greenbrier Rail Services (Omaha, NE)': 'GBR-OMAHA',
  'H.C. Chandler and Son, Inc. (Plantersville)': 'HCC-PLANTERSVILLE',
  'Iron Horse Rail Services (Beaumont)': 'IRONHORSE-BEAUMONT',
  'KRS Katahdin Railcar Services  (Bangor)': 'KRS-BANGOR',
  'Midwest Railcar Repair, Inc. (Brandon (Corson))': 'MWR-BRANDON',
  'PSC Repair (Beaumont, TX)': 'PSC-BEAUMONT',
  'Procor Limited (N. Van)': 'PRO-NVAN',
  'Procor Limited (Joffre)': 'PRO-JOFFRE',
  'Procor Limited (Sarnia)': 'PRO-SARNIA',
  'Procor - Transmark (Lethbridge, AB)': 'PRO-LETHBRIDGE',
  'Rescar (Savanna, IL)': 'RESCAR-SAVANNA',
  'TLC Rail Services/Inserv-Wright City (Wright City, OK)': 'TLC-WRIGHTCITY',
  'TMC Engineering Services (Houston, TX)': 'TMC-HOUSTON',
  'TNT Repair Services (Longview)': 'TNT-LONGVIEW',
  'Transco (Texarkana)': 'TRC-TEXARKANA',
  'Transco Rail (Sayre)': 'TRC-SAYRE',
  'Transco Railway (Oelwein)': 'TRC-OELWEIN',
  'Transco Railway Products, Inc. (Miles City)': 'TRC-MILESCITY',
  'Transco-Sheldon, TX (Houston)': 'TRC-SHELDON',
  'Transitech, Inc. (Fordyce)': 'TRANSITECH-FORDYCE',
  'Trinity Industries, Inc. (Ft. Worth)': 'TRI-FTWORTH',
  'Trinity Industries, Inc. (Saginaw)': 'TRI-SAGINAW',
  'Trinity Rail Services (Shell Rock, IA)': 'TRI-SHELLROCK',
  'Trinity Rail - Sunray (Sunray, TX)': 'TRI-SUNRAY',
  'Red River Coatings (Nash, TX)': 'RRC-NASH',
  'Rescar #380 (Deer Park)': 'RESCAR-DEERPARK',
  'Texana Midway Tank Cleaning (Texarkana, TX)': 'TEXANA-TEXARKANA',
  'VLS RECOVERY SERVICES  - Hockley (hockley)': 'VLS-HOCKLEY',
};

// Get network by shop code
export function getNetworkForShopCode(shopCode: string): ShopNetwork | null {
  for (const network of ALL_NETWORKS) {
    const location = network.locations.find(loc => loc.code === shopCode);
    if (location) {
      return network;
    }
  }
  return null;
}

// Get shop location by code
export function getShopLocationByCode(shopCode: string): ShopLocation | null {
  for (const network of ALL_NETWORKS) {
    const location = network.locations.find(loc => loc.code === shopCode);
    if (location) {
      return location;
    }
  }
  return null;
}

// Get all shop locations flattened
export function getAllShopLocations(): (ShopLocation & { networkId: string; networkName: string; isAitxInternal: boolean })[] {
  const locations: (ShopLocation & { networkId: string; networkName: string; isAitxInternal: boolean })[] = [];

  for (const network of ALL_NETWORKS) {
    for (const location of network.locations) {
      locations.push({
        ...location,
        networkId: network.id,
        networkName: network.name,
        isAitxInternal: network.isAitxInternal,
      });
    }
  }

  return locations;
}

// Calculate total AITX capacity
export function getAitxTotalCapacity(): { monthly: number; annual: number } {
  const monthly = AITX_NETWORK.locations.reduce((sum, loc) => sum + loc.monthlyCapacity, 0);
  return { monthly, annual: monthly * 12 };
}

// Calculate total 3P capacity
export function getThirdPartyTotalCapacity(): { monthly: number; annual: number } {
  const monthly = THIRD_PARTY_NETWORKS.reduce(
    (sum, network) => sum + network.locations.reduce((locSum, loc) => locSum + loc.monthlyCapacity, 0),
    0
  );
  return { monthly, annual: monthly * 12 };
}

// Calculate system total capacity
export function getSystemTotalCapacity(): { monthly: number; annual: number; aitxPercent: number; thirdPartyPercent: number } {
  const aitx = getAitxTotalCapacity();
  const thirdParty = getThirdPartyTotalCapacity();
  const total = aitx.monthly + thirdParty.monthly;

  return {
    monthly: total,
    annual: total * 12,
    aitxPercent: Math.round((aitx.monthly / total) * 100),
    thirdPartyPercent: Math.round((thirdParty.monthly / total) * 100),
  };
}

// Default S&OP Planning Parameters
export const SOP_PLANNING_DEFAULTS = {
  planningYear: new Date().getFullYear(),
  demandRegisterYearRange: { prior: 1, current: 1, following: 1 }, // -1, 0, +1 years
  utilizationTarget: 0.90,
  aitxCostPremium: 1.379,
  planningHorizonMonths: 18,
  tankCarPercentage: 65,
  freightCarPercentage: 35,
};

// Team assignments based on qualification type
export const TEAM_ASSIGNMENTS = {
  'Full Qual': 'qualification',     // Qual team
  'Partial Qual': 'in_service_repairs', // In-service repairs team
} as const;

export type TeamAssignment = typeof TEAM_ASSIGNMENTS[keyof typeof TEAM_ASSIGNMENTS];
